// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	models "infotecsTest/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// TransactionsReceiver is an autogenerated mock type for the TransactionsReceiver type
type TransactionsReceiver struct {
	mock.Mock
}

// GetNTransactions provides a mock function with given fields: N
func (_m *TransactionsReceiver) GetNTransactions(N int) ([]models.Transaction, error) {
	ret := _m.Called(N)

	if len(ret) == 0 {
		panic("no return value specified for GetNTransactions")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]models.Transaction, error)); ok {
		return rf(N)
	}
	if rf, ok := ret.Get(0).(func(int) []models.Transaction); ok {
		r0 = rf(N)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(N)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionsReceiver creates a new instance of TransactionsReceiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionsReceiver(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionsReceiver {
	mock := &TransactionsReceiver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
